copy index and css
Yemisirach/Review_Project pull request #1
Opened 2022-12-08 11:48 UTC by Yemisirach

2022-12-08 13:49 UTC, Yemisirach reviewed
[check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) [check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header)

2022-12-08 13:49 UTC, Yemisirach commented on index.html
> +    <section>
**# Optional Suggestion** 

- [ ] I recommend you to use heeder tag for Toolbar section instead of section tag. typically the header tag is used as a page header.  [check here link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more information.

2022-12-08 13:49 UTC, Yemisirach commented on css/style.css
> +@media (max-width: 1500px) {
The design
![designnn](https://user-images.githubusercontent.com/104437323/206456664-6c73df58-5f71-4965-96c2-e1f2a7490340.GIF)
- [ ] As stated the project requirement you must stick to the design as much as possible. You chooses a break point is not responsive.
Your work
![you design](https://user-images.githubusercontent.com/104437323/206460381-6103c63e-1e63-4ee6-b5db-11c7bfd1c756.GIF)

2022-12-12 08:02 UTC, Olamarx requested changes
Hi @Yemisirach,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- GitHub review feature ✔️
- inline comments ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-12 08:02 UTC, Olamarx commented on css/style.css
> +@media (max-width: 1500px) {
> The design ![designnn](https://user-images.githubusercontent.com/104437323/206456664-6c73df58-5f71-4965-96c2-e1f2a7490340.GIF)
> 
> * [ ]  As stated the project requirement you must stick to the design as much as possible. Your built-in design is not responsive.
>   Your work
>   ![you design](https://user-images.githubusercontent.com/104437323/206460381-6103c63e-1e63-4ee6-b5db-11c7bfd1c756.GIF)
> * [ ]   Adjust the font size, padding, and margin of "These are some of the my projects" look like a design.

- [ ] I would advise you to make recommendations politely and not as a command. It can look like "I think it would be better to use semantic tags" and also give reasons for your required changes so that student can understand your view clearly.

2022-12-12 08:35 UTC, Abenezer-Tilahun approved these changes
Hi @Yemisirach 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ Descriptive PR title.
✔️ You used correct Github-Flow.
✔️ Inline comments are present
✔️ The comments are very polite


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-24 19:39 UTC, merged